---

services:
  prometheus:
    image: "prom/prometheus:v2.53.1"
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./web.yml:/etc/prometheus/web.yml:ro"
      - "prometheus:/prometheus"
    ports:
      - "127.0.0.1:9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml

volumes:
  prometheus: {}
