---

services:
  vault:
    image: vault:1.13.3
    cap_add:
      - IPC_LOCK
    restart: always
    command:
      - vault
      - server
      - -config
      - /vault.hcl
    volumes: 
      - "./vault.hcl:/vault.hcl:ro"
      - "<tls keyfile>:/vault.key:ro"
      - "<tls certfile>:/vault.crt:ro"
      - "vault-data:/vault/file"
    ports:
      - "0.0.0.0:8200:8200"

volumes:
  vault-data: {}
