---

services:
  nginx:
    image: "nginx:stable"
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "0.0.0.0:53:53"
      - "0.0.0.0:53:53/udp"

  coredns:
    image: "coredns/coredns:1.11.1"
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
    command:
      - -conf
      - /Corefile
    restart: always
    volumes: 
      - "./Corefile:/Corefile:ro"
      - "./zones:/zones:ro"
