---

services:
  node-exporter:
    image: "prom/node-exporter:v1.8.2"
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - --path.rootfs=/host

