name: build evindunn/chronyd:latest

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-image.yml'
      - 'shared/**'
      - '.github/workflows/chronyd.yml'
      - 'chronyd/**'
  workflow_dispatch: {}

jobs:
  build:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip-build]') }}
    uses: ./.github/workflows/build-image.yml
    with:
      image: evindunn/chronyd
      tag: latest
      context: chronyd
    secrets: inherit
