name: build evindunn/chronyd:latest

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-image.yml'
      - '.github/workflows/wait-for-parent-image.yml'
      - 'shared/**'
      - '.github/workflows/chronyd.yml'
      - 'chronyd/**'
  workflow_dispatch: {}

concurrency:
  group: 'image-build-evindunn-chronyd-latest'
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      image: evindunn/chronyd
      tag: latest
      context: chronyd
    secrets: inherit
