name: build evindunn/debian:trixie-slim

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-image-base.yml'
      - '.github/workflows/check_readme_image.py'
      - '.github/workflows/debian-trixie-slim.yml'
      - 'debian-trixie-slim/**'
      - 'shared/**'
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: evindunn/debian
      tag: trixie-slim
      context: debian-trixie-slim
    secrets: inherit
