name: build evindunn/python3

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-image.yml'
      - '.github/workflows/build-image-children.yml'
      - 'scripts/**'
      - 'shared/**'
      - '.github/workflows/python3.yml'
      - 'python3/**'
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      image: evindunn/python3
      tag: latest
      context: python3
    secrets: inherit

  build_children:
    needs: build
    uses: ./.github/workflows/build-image-children.yml
    with:
      parent_image: evindunn/python3:latest
