name: build evindunn/python3

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-image.yml'
      - '.github/workflows/build-image-children.yml'
      - '.github/workflows/wait-for-parent-image.yml'
      - 'scripts/**'
      - 'shared/**'
      - '.github/workflows/python3.yml'
      - 'python3/**'
  workflow_dispatch: {}

jobs:
  wait_for_parent_image:
    uses: ./.github/workflows/wait-for-parent-image.yml
    with:
      context: python3

  build:
    needs: wait_for_parent_image
    uses: ./.github/workflows/build-image.yml
    with:
      image: evindunn/python3
      tag: latest
      context: python3
    secrets: inherit

  build_children:
    needs: build
    uses: ./.github/workflows/build-image-children.yml
    with:
      image: evindunn/python3
      tag: latest
