name: build evindunn/vault-agent:latest

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-image-base.yml'
      - 'shared/**'
      - '.github/workflows/vault-agent.yml'
      - 'vault-agent/**'
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: evindunn/vault-agent
      tag: latest
      context: vault-agent
    secrets: inherit
