name: build evindunn/vault-agent:latest

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-image.yml'
      - '.github/workflows/wait-for-parent-image.yml'
      - 'shared/**'
      - '.github/workflows/vault-agent.yml'
      - 'vault-agent/**'
  workflow_dispatch: {}

concurrency:
  group: 'image-build-evindunn-vault-agent-latest'
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      image: evindunn/vault-agent
      tag: latest
      context: vault-agent
    secrets: inherit
